"""Tinyprobe - Generated by embgen.

DO NOT EDIT - This file is auto-generated.
"""

from collections.abc import Callable
from dataclasses import dataclass
from enum import Enum, IntEnum
from typing import Any

CMD_ONEOF_NAME = "args"
"""Name of the command oneof field in the generated protobuf message."""

MAX_COMMANDS_PER_PACKET = 60
"""Maximum number of commands allowed in a single request packet."""

METHOD_NAMES = (
    "controlpower",
    "controlspi",
    "delayms",
    "delayns",
    "loop",
    "ping",
    "setloglevel",
    "triggershot",
    "writeafe",
    "writefpga",
    "writetx",
)

METHOD_FIELD_NAMES: dict[str, tuple[str, ...]] = {
    "controlpower": (
        "domain",
        "enable",
    ),
    "controlspi": ("domain",),
    "delayms": ("delay",),
    "delayns": ("delay",),
    "loop": (
        "iterations",
        "command_index",
    ),
    "ping": ("probe_id",),
    "setloglevel": ("level",),
    "triggershot": (
        "num_shots",
        "num_packets",
        "delay_dcdc_off_ns",
        "delay_read_fifo_ns",
        "callback_id",
        "software_trigger",
        "pwd_dcdc_at_rx",
    ),
    "writeafe": (
        "dtgc",
        "address",
        "value",
    ),
    "writefpga": (
        "address",
        "value",
    ),
    "writetx": (
        "address",
        "value",
    ),
}

METHOD_RETURN_FIELD_NAMES: dict[str, tuple[str, ...]] = {
    "controlpower": (),
    "controlspi": (),
    "delayms": (),
    "delayns": (),
    "loop": (),
    "ping": (),
    "setloglevel": (),
    "triggershot": (),
    "writeafe": (),
    "writefpga": (),
    "writetx": (),
}


class RPCStatus(IntEnum):
    """Generic response status codes returned by the generated NanoPB RPC API."""

    OK = 0
    INVALID_ARGUMENT = 1
    INVALID_STATE = 2
    TIMEOUT = 3
    UNKNOWN_ERROR = 4


@dataclass(frozen=True)
class Method:
    """Generated NanoPB method payload."""

    method: str
    params: dict[str, Any] | None = None


def proto_scalar(value: Any) -> Any:
    """Convert enum values to their raw scalar representation."""

    if isinstance(value, Enum):
        return value.value
    return value


def method_field_names(method: str) -> tuple[str, ...]:
    """Return the ordered parameter names for a generated method."""

    try:
        return METHOD_FIELD_NAMES[method]
    except KeyError as exc:
        raise AttributeError(f"Method '{method}' is not supported") from exc


def method_return_field_names(method: str) -> tuple[str, ...]:
    """Return the ordered result field names for a generated method."""

    try:
        return METHOD_RETURN_FIELD_NAMES[method]
    except KeyError as exc:
        raise AttributeError(f"Method '{method}' is not supported") from exc


def method_defaults(method: str) -> dict[str, Any]:
    """Return the configured default arguments for a generated method."""

    return METHOD_DEFAULTS.get(method, {})


def status_name(status: int) -> str:
    """Map a numeric status code to its symbolic name."""

    try:
        return RPCStatus(status).name
    except ValueError:
        return f"UNKNOWN_STATUS_{status}"


def is_ok_status(status: int) -> bool:
    """Return whether a numeric status code represents success."""

    return int(status) == int(RPCStatus.OK)


class TinyprobeMethods:
    """Factory for the generated Tinyprobe NanoPB methods."""

    class Powerdomain(IntEnum):
        """Power domain to control"""

        LVDS_2V5 = 0
        POS_HV = 1
        NEG_HV = 2
        NEG_5V = 3
        PLL_PWD = 4

    class Spidomain(IntEnum):
        """SPI domain to switch to"""

        PLL = 0
        FPGA = 1
        AFE = 2
        TX = 3

    class Loglevel(IntEnum):
        """Log level to set"""

        TRACE = 0
        DEBUG = 1
        INFO = 2
        WARN = 3
        ERROR = 4
        FATAL = 5

    def __init__(self, add_callback: Callable[[Method], None] | None = None):
        """Initialize the method factory.

        Args:
            add_callback: Optional callback invoked for each created method.
        """

        self._add_callback = add_callback

    def _add(self, method: Method) -> None:
        """Forward a generated method to the optional callback."""

        if self._add_callback is not None:
            self._add_callback(method)

    @property
    def methods(self) -> list[str]:
        """Return the available generated NanoPB method names."""

        return list(METHOD_NAMES)

    def controlpower(
        self,
        domain: Powerdomain,
        enable: bool,
    ) -> Method:
        """Control the state of a power domain

        Args:
            domain: Power domain to control
            enable: Enable (true) or disable (false) the power domain

        Returns:
            The generated request payload for ``controlpower``.
        """

        result = Method(
            method="controlpower",
            params={
                "domain": proto_scalar(domain),
                "enable": enable,
            },
        )
        self._add(result)
        return result

    def controlspi(
        self,
        domain: Spidomain,
    ) -> Method:
        """Switch the SPI MUX

        Args:
            domain: SPI domain to switch to

        Returns:
            The generated request payload for ``controlspi``.
        """

        result = Method(
            method="controlspi",
            params={
                "domain": proto_scalar(domain),
            },
        )
        self._add(result)
        return result

    def delayms(
        self,
        delay: int,
    ) -> Method:
        """Delay for a specified number of milliseconds

        Args:
            delay: Number of milliseconds to delay

        Returns:
            The generated request payload for ``delayms``.
        """

        result = Method(
            method="delayms",
            params={
                "delay": delay,
            },
        )
        self._add(result)
        return result

    def delayns(
        self,
        delay: int,
    ) -> Method:
        """Delay for a specified number of nanoseconds

        Args:
            delay: Number of nanoseconds to delay

        Returns:
            The generated request payload for ``delayns``.
        """

        result = Method(
            method="delayns",
            params={
                "delay": delay,
            },
        )
        self._add(result)
        return result

    def loop(
        self,
        iterations: int,
        command_index: int,
    ) -> Method:
        """Go back in the command queue to a previous command for a given number of iterations

        Args:
            iterations: Number of iterations to loop
            command_index: Index of the command to loop back to (0-based)

        Returns:
            The generated request payload for ``loop``.
        """

        result = Method(
            method="loop",
            params={
                "iterations": iterations,
                "command_index": command_index,
            },
        )
        self._add(result)
        return result

    def ping(
        self,
        probe_id: int = 1,
    ) -> Method:
        """Ping the device

        Args:
            probe_id: ID of the probe to ping Defaults to 1.

        Returns:
            The generated request payload for ``ping``.
        """

        result = Method(
            method="ping",
            params={
                "probe_id": probe_id,
            },
        )
        self._add(result)
        return result

    def setloglevel(
        self,
        level: Loglevel,
    ) -> Method:
        """Set the log level on the device

        Args:
            level: Log level to set

        Returns:
            The generated request payload for ``setloglevel``.
        """

        result = Method(
            method="setloglevel",
            params={
                "level": proto_scalar(level),
            },
        )
        self._add(result)
        return result

    def triggershot(
        self,
        num_shots: int = 1,
        num_packets: int = 82,
        delay_dcdc_off_ns: int = 6100,
        delay_read_fifo_ns: int = 200000,
        callback_id: int = 65535,
        software_trigger: bool = True,
        pwd_dcdc_at_rx: bool = True,
    ) -> Method:
        """Trigger a shot

        Args:
            num_shots: Number of shots to trigger Defaults to 1.
            num_packets: Number of packets to expect Defaults to 82.
            delay_dcdc_off_ns: Delay before DCDC is disabled, in nanoseconds Defaults to 6100.
            delay_read_fifo_ns: Delay before FIFO read, in nanoseconds Defaults to 200000.
            callback_id: Callback packet identifier (0-65535), or 65535 for no callback Defaults to 65535.
            software_trigger: True to use a software trigger Defaults to True.
            pwd_dcdc_at_rx: True to power down DCDC during RX Defaults to True.

        Returns:
            The generated request payload for ``triggershot``.
        """

        result = Method(
            method="triggershot",
            params={
                "num_shots": num_shots,
                "num_packets": num_packets,
                "delay_dcdc_off_ns": delay_dcdc_off_ns,
                "delay_read_fifo_ns": delay_read_fifo_ns,
                "callback_id": callback_id,
                "software_trigger": software_trigger,
                "pwd_dcdc_at_rx": pwd_dcdc_at_rx,
            },
        )
        self._add(result)
        return result

    def writeafe(
        self,
        dtgc: bool,
        address: int,
        value: int,
    ) -> Method:
        """Write to an AFE register

        Args:
            dtgc: Register map to write (true for DTGC, false for GLB)
            address: Address of the AFE register to write
            value: Value to write to the AFE register

        Returns:
            The generated request payload for ``writeafe``.
        """

        result = Method(
            method="writeafe",
            params={
                "dtgc": dtgc,
                "address": address,
                "value": value,
            },
        )
        self._add(result)
        return result

    def writefpga(
        self,
        address: int,
        value: int,
    ) -> Method:
        """Write to a FPGA register

        Args:
            address: Address of the FPGA register to write
            value: Value to write to the FPGA register

        Returns:
            The generated request payload for ``writefpga``.
        """

        result = Method(
            method="writefpga",
            params={
                "address": address,
                "value": value,
            },
        )
        self._add(result)
        return result

    def writetx(
        self,
        address: int,
        value: int,
    ) -> Method:
        """Write to a TX register

        Args:
            address: Address of the TX register to write
            value: Value to write to the TX register

        Returns:
            The generated request payload for ``writetx``.
        """

        result = Method(
            method="writetx",
            params={
                "address": address,
                "value": value,
            },
        )
        self._add(result)
        return result


METHOD_DEFAULTS: dict[str, dict[str, Any]] = {
    "controlpower": {},
    "controlspi": {},
    "delayms": {},
    "delayns": {},
    "loop": {},
    "ping": {
        "probe_id": 1,
    },
    "setloglevel": {},
    "triggershot": {
        "num_shots": 1,
        "num_packets": 82,
        "delay_dcdc_off_ns": 6100,
        "delay_read_fifo_ns": 200000,
        "callback_id": 65535,
        "software_trigger": True,
        "pwd_dcdc_at_rx": True,
    },
    "writeafe": {},
    "writefpga": {},
    "writetx": {},
}
