"""
Regmap_FPGA - Auto-generated register map definitions.

This file is auto-generated by embgen. Do not edit manually.
"""

from enum import Enum as BaseEnum

try:
    # Try relative import first for better compatibility when used as a package
    from..regmap_base import (
        RegisterMapInterface,
        RegisterMap,
        Register,
        BitField,
        Access,
        Interface,
    )
except ImportError:
    # Fallback to absolute import if relative import fails (e.g., when run as a script)
    from regmap_base import (
        RegisterMapInterface,
        RegisterMap,
        Register,
        BitField,
        Access,
        Interface,
    )

__all__ = ["Regmap_FPGA", "Interface", "RegisterMapInterface"]


class Regmap_FPGA(RegisterMap):
    """Register map for Regmap_FPGA."""

    class EnumCmd(BaseEnum):
        """Enum for bitfield CMD.CMD"""

        NOP = 0
        START = 1
        SW_RESET = 2
        RD_EN = 3
        ECHO = 4

    class EnumPrm(BaseEnum):
        """Enum for bitfield PRM.PLL_CONFIG_REG"""

        PLL_POWERDOWN = 0
        PLL_ARST_N = 1

    class EnumFen(BaseEnum):
        """Enum for bitfield FEN.WAVEFORM_GEN_REG_5"""

        DISABLE_REFRESH = 0
        ENABLE_REFRESH = 1

    class EnumEit(BaseEnum):
        """Enum for bitfield EIT.EXT_INT_TRIG_REG"""

        INTERNAL_SW_TRIGGER = 0
        EXTERNAL_TRIGGER = 1

    class EnumMim(BaseEnum):
        """Enum for bitfield MIM.EXT_INT_TRIG_REG"""

        MCU_INT_FIFO_WR_DONE = 0
        MCU_INT_AFE_TX_TRIG = 1
        MCU_INT_TX_BF_SYNC = 2
        MCU_INT_EXT_TRIG = 3

    class EnumOtm(BaseEnum):
        """Enum for bitfield OTM.EXT_INT_TRIG_REG"""

        TRIG_OUT_TX_BF_SYNC = 0
        TRIG_OUT_AFE_TX_TRIG = 1
        TRIG_OUT_PLL_LOCK = 2
        TRIG_OUT_FIFO_WR_DONE = 3

    def __init__(self, interface: RegisterMapInterface) -> None:
        self._interface = interface
        self.cmd = RegisterCMD(self._interface)
        self.pll_config_reg = RegisterPLL_CONFIG_REG(self._interface)
        self.lvds_ch_en = RegisterLVDS_CH_EN(self._interface)
        self.waveform_gen_reg_1 = RegisterWAVEFORM_GEN_REG_1(self._interface)
        self.waveform_gen_reg_2 = RegisterWAVEFORM_GEN_REG_2(self._interface)
        self.waveform_gen_reg_3 = RegisterWAVEFORM_GEN_REG_3(self._interface)
        self.tgc_reg_1 = RegisterTGC_REG_1(self._interface)
        self.tgc_reg_2 = RegisterTGC_REG_2(self._interface)
        self.tgc_reg_3 = RegisterTGC_REG_3(self._interface)
        self.tgc_reg_4 = RegisterTGC_REG_4(self._interface)
        self.afe_tx_rst_reg = RegisterAFE_TX_RST_REG(self._interface)
        self.waveform_gen_reg_4 = RegisterWAVEFORM_GEN_REG_4(self._interface)
        self.waveform_gen_reg_5 = RegisterWAVEFORM_GEN_REG_5(self._interface)
        self.ext_int_trig_reg = RegisterEXT_INT_TRIG_REG(self._interface)


# ============================================================================


class BitFieldCMDCmd(BitField):
    """BitField CMD in Register CMD

    Command byte controlling acquisition and helper functions.
    """

    _name = "CMD"
    _description = "Command byte controlling acquisition and helper functions."
    _reset = 0
    _width = 8
    _offset = 0
    _enums = Regmap_FPGA.EnumCmd


class RegisterCMD(Register):
    """Register CMD

    Address: 0x0000 (0)

    Command Register
    """

    _name = "CMD"
    _description = "Command Register"
    _address = 0
    _access = Access.RW

    def __init__(self, interface: RegisterMapInterface) -> None:
        self._interface = interface

        # Create instances of bitfields for this register instance
        self.cmd = BitFieldCMDCmd()
        self.cmd._set_interface(self._address, interface, self._access)


class BitFieldPLL_CONFIG_REGTx_mux(BitField):
    """BitField TX_MUX in Register PLL_CONFIG_REG

    TX Beamforming clock: 0 = 20 MHz, 1 = 100 MHz.
    """

    _name = "TX_MUX"
    _description = "TX Beamforming clock: 0 = 20 MHz, 1 = 100 MHz."
    _reset = 0
    _width = 1
    _offset = 0
    _enums = None


class BitFieldPLL_CONFIG_REGAfe_mux(BitField):
    """BitField AFE_MUX in Register PLL_CONFIG_REG

    AFE clock: 0 = 20 MHz (10 MHz sampling), 1 = 60 MHz (30 MHz sampling).
    """

    _name = "AFE_MUX"
    _description = "AFE clock: 0 = 20 MHz (10 MHz sampling), 1 = 60 MHz (30 MHz sampling)."
    _reset = 0
    _width = 1
    _offset = 1
    _enums = None


class BitFieldPLL_CONFIG_REGFpga_mux(BitField):
    """BitField FPGA_MUX in Register PLL_CONFIG_REG

    FPGA core clock: 0 = 10 MHz, 1 = 20 MHz.
    """

    _name = "FPGA_MUX"
    _description = "FPGA core clock: 0 = 10 MHz, 1 = 20 MHz."
    _reset = 0
    _width = 1
    _offset = 2
    _enums = None


class BitFieldPLL_CONFIG_REGTx_ctrl(BitField):
    """BitField TX_CTRL in Register PLL_CONFIG_REG

    Multiplexer for PLL GL0 enable signal: 0 = Controlled by TX_EN, 1 = Defined by tx_clk_buf_en_wave_gen
    """

    _name = "TX_CTRL"
    _description = "Multiplexer for PLL GL0 enable signal: 0 = Controlled by TX_EN, 1 = Defined by tx_clk_buf_en_wave_gen"
    _reset = 0
    _width = 1
    _offset = 3
    _enums = None


class BitFieldPLL_CONFIG_REGTx_en(BitField):
    """BitField TX_EN in Register PLL_CONFIG_REG

    PLL GL0 enable signal (active high) for TX clock output.
    """

    _name = "TX_EN"
    _description = "PLL GL0 enable signal (active high) for TX clock output."
    _reset = 0
    _width = 1
    _offset = 4
    _enums = None


class BitFieldPLL_CONFIG_REGAfe_ctrl(BitField):
    """BitField AFE_CTRL in Register PLL_CONFIG_REG

    Multiplexer for PLL GL1 enable signal: 0 = Controlled by AFE_EN, 1 = Defined by afe_clk_buf_en_wave_gen
    """

    _name = "AFE_CTRL"
    _description = "Multiplexer for PLL GL1 enable signal: 0 = Controlled by AFE_EN, 1 = Defined by afe_clk_buf_en_wave_gen"
    _reset = 0
    _width = 1
    _offset = 5
    _enums = None


class BitFieldPLL_CONFIG_REGAfe_en(BitField):
    """BitField AFE_EN in Register PLL_CONFIG_REG

    PLL GL1 enable signal (active high) for AFE clock output.
    """

    _name = "AFE_EN"
    _description = "PLL GL1 enable signal (active high) for AFE clock output."
    _reset = 0
    _width = 1
    _offset = 6
    _enums = None


class BitFieldPLL_CONFIG_REGPrm(BitField):
    """BitField PRM in Register PLL_CONFIG_REG

    SPI SS alt-func mux: drives either PLL async reset or power-down.
    """

    _name = "PRM"
    _description = "SPI SS alt-func mux: drives either PLL async reset or power-down."
    _reset = 0
    _width = 1
    _offset = 7
    _enums = Regmap_FPGA.EnumPrm


class RegisterPLL_CONFIG_REG(Register):
    """Register PLL_CONFIG_REG

    Address: 0x0001 (1)

    PLL Configuration Register
    """

    _name = "PLL_CONFIG_REG"
    _description = "PLL Configuration Register"
    _address = 1
    _access = Access.RW

    def __init__(self, interface: RegisterMapInterface) -> None:
        self._interface = interface

        # Create instances of bitfields for this register instance
        self.tx_mux = BitFieldPLL_CONFIG_REGTx_mux()
        self.tx_mux._set_interface(self._address, interface, self._access)
        self.afe_mux = BitFieldPLL_CONFIG_REGAfe_mux()
        self.afe_mux._set_interface(self._address, interface, self._access)
        self.fpga_mux = BitFieldPLL_CONFIG_REGFpga_mux()
        self.fpga_mux._set_interface(self._address, interface, self._access)
        self.tx_ctrl = BitFieldPLL_CONFIG_REGTx_ctrl()
        self.tx_ctrl._set_interface(self._address, interface, self._access)
        self.tx_en = BitFieldPLL_CONFIG_REGTx_en()
        self.tx_en._set_interface(self._address, interface, self._access)
        self.afe_ctrl = BitFieldPLL_CONFIG_REGAfe_ctrl()
        self.afe_ctrl._set_interface(self._address, interface, self._access)
        self.afe_en = BitFieldPLL_CONFIG_REGAfe_en()
        self.afe_en._set_interface(self._address, interface, self._access)
        self.prm = BitFieldPLL_CONFIG_REGPrm()
        self.prm._set_interface(self._address, interface, self._access)


class BitFieldLVDS_CH_ENLvds_ch_en(BitField):
    """BitField LVDS_CH_EN in Register LVDS_CH_EN

    Enable mask for 16 LVDS receivers; also gates which FIFOs accept writes and are later readable via SPI. If all 0, bit/frame clock buffers auto-disable.
    """

    _name = "LVDS_CH_EN"
    _description = "Enable mask for 16 LVDS receivers; also gates which FIFOs accept writes and are later readable via SPI. If all 0, bit/frame clock buffers auto-disable."
    _reset = 0
    _width = 16
    _offset = 0
    _enums = None


class BitFieldLVDS_CH_ENFifo_rd_wr_cnt(BitField):
    """BitField FIFO_RD_WR_CNT in Register LVDS_CH_EN

    Samples per channel to write to and read from FIFOs.
    """

    _name = "FIFO_RD_WR_CNT"
    _description = "Samples per channel to write to and read from FIFOs."
    _reset = 0
    _width = 12
    _offset = 16
    _enums = None


class BitFieldLVDS_CH_ENClk_ctl_tx(BitField):
    """BitField CLK_CTL_TX in Register LVDS_CH_EN

    TX chip clock buffer {0=WF gen control, 1=force ON}
    """

    _name = "CLK_CTL_TX"
    _description = "TX chip clock buffer {0=WF gen control, 1=force ON}"
    _reset = 0
    _width = 1
    _offset = 30
    _enums = None


class BitFieldLVDS_CH_ENClk_ctl_afe(BitField):
    """BitField CLK_CTL_AFE in Register LVDS_CH_EN

    AFE clock buffer {0=WF gen control, 1=force ON}.
    """

    _name = "CLK_CTL_AFE"
    _description = "AFE clock buffer {0=WF gen control, 1=force ON}."
    _reset = 0
    _width = 1
    _offset = 31
    _enums = None


class RegisterLVDS_CH_EN(Register):
    """Register LVDS_CH_EN

    Address: 0x0002 (2)

    LVDS Channel Enable
    """

    _name = "LVDS_CH_EN"
    _description = "LVDS Channel Enable"
    _address = 2
    _access = Access.RW

    def __init__(self, interface: RegisterMapInterface) -> None:
        self._interface = interface

        # Create instances of bitfields for this register instance
        self.lvds_ch_en = BitFieldLVDS_CH_ENLvds_ch_en()
        self.lvds_ch_en._set_interface(self._address, interface, self._access)
        self.fifo_rd_wr_cnt = BitFieldLVDS_CH_ENFifo_rd_wr_cnt()
        self.fifo_rd_wr_cnt._set_interface(self._address, interface, self._access)
        self.clk_ctl_tx = BitFieldLVDS_CH_ENClk_ctl_tx()
        self.clk_ctl_tx._set_interface(self._address, interface, self._access)
        self.clk_ctl_afe = BitFieldLVDS_CH_ENClk_ctl_afe()
        self.clk_ctl_afe._set_interface(self._address, interface, self._access)


class BitFieldWAVEFORM_GEN_REG_1Tr_sw_sleep_time(BitField):
    """BitField TR_SW_SLEEP_TIME in Register WAVEFORM_GEN_REG_1

    TX switch (TR) sleep time after sync event.
    """

    _name = "TR_SW_SLEEP_TIME"
    _description = "TX switch (TR) sleep time after sync event."
    _reset = 0
    _width = 8
    _offset = 0
    _enums = None


class BitFieldWAVEFORM_GEN_REG_1Tr_sw_wkp_time(BitField):
    """BitField TR_SW_WKP_TIME in Register WAVEFORM_GEN_REG_1

    TX switch (TR) wake-up time before sync event.
    """

    _name = "TR_SW_WKP_TIME"
    _description = "TX switch (TR) wake-up time before sync event."
    _reset = 0
    _width = 8
    _offset = 8
    _enums = None


class BitFieldWAVEFORM_GEN_REG_1Sync_period(BitField):
    """BitField SYNC_PERIOD in Register WAVEFORM_GEN_REG_1

    Synchronization period of the waveform generator (defines PRF).
    """

    _name = "SYNC_PERIOD"
    _description = "Synchronization period of the waveform generator (defines PRF)."
    _reset = 0
    _width = 16
    _offset = 16
    _enums = None


class RegisterWAVEFORM_GEN_REG_1(Register):
    """Register WAVEFORM_GEN_REG_1

    Address: 0x0003 (3)

    Waveform Generator Reg 1
    """

    _name = "WAVEFORM_GEN_REG_1"
    _description = "Waveform Generator Reg 1"
    _address = 3
    _access = Access.RW

    def __init__(self, interface: RegisterMapInterface) -> None:
        self._interface = interface

        # Create instances of bitfields for this register instance
        self.tr_sw_sleep_time = BitFieldWAVEFORM_GEN_REG_1Tr_sw_sleep_time()
        self.tr_sw_sleep_time._set_interface(self._address, interface, self._access)
        self.tr_sw_wkp_time = BitFieldWAVEFORM_GEN_REG_1Tr_sw_wkp_time()
        self.tr_sw_wkp_time._set_interface(self._address, interface, self._access)
        self.sync_period = BitFieldWAVEFORM_GEN_REG_1Sync_period()
        self.sync_period._set_interface(self._address, interface, self._access)


class BitFieldWAVEFORM_GEN_REG_2Afe_clk_on_time(BitField):
    """BitField AFE_CLK_ON_TIME in Register WAVEFORM_GEN_REG_2

    Duration the AFE clock stays on around sync.
    """

    _name = "AFE_CLK_ON_TIME"
    _description = "Duration the AFE clock stays on around sync."
    _reset = 0
    _width = 16
    _offset = 0
    _enums = None


class BitFieldWAVEFORM_GEN_REG_2Afe_wkp_time(BitField):
    """BitField AFE_WKP_TIME in Register WAVEFORM_GEN_REG_2

    AFE wake-up lead time before sync.
    """

    _name = "AFE_WKP_TIME"
    _description = "AFE wake-up lead time before sync."
    _reset = 0
    _width = 8
    _offset = 16
    _enums = None


class RegisterWAVEFORM_GEN_REG_2(Register):
    """Register WAVEFORM_GEN_REG_2

    Address: 0x0004 (4)

    Waveform Generator Reg 2
    """

    _name = "WAVEFORM_GEN_REG_2"
    _description = "Waveform Generator Reg 2"
    _address = 4
    _access = Access.RW

    def __init__(self, interface: RegisterMapInterface) -> None:
        self._interface = interface

        # Create instances of bitfields for this register instance
        self.afe_clk_on_time = BitFieldWAVEFORM_GEN_REG_2Afe_clk_on_time()
        self.afe_clk_on_time._set_interface(self._address, interface, self._access)
        self.afe_wkp_time = BitFieldWAVEFORM_GEN_REG_2Afe_wkp_time()
        self.afe_wkp_time._set_interface(self._address, interface, self._access)


class BitFieldWAVEFORM_GEN_REG_3Afe_data_acq_time(BitField):
    """BitField AFE_DATA_ACQ_TIME in Register WAVEFORM_GEN_REG_3

    Duration of AFE data acquisition window.
    """

    _name = "AFE_DATA_ACQ_TIME"
    _description = "Duration of AFE data acquisition window."
    _reset = 0
    _width = 16
    _offset = 0
    _enums = None


class BitFieldWAVEFORM_GEN_REG_3Capture_delay(BitField):
    """BitField CAPTURE_DELAY in Register WAVEFORM_GEN_REG_3

    Delay from TX sync to start of AFE acquisition.
    """

    _name = "CAPTURE_DELAY"
    _description = "Delay from TX sync to start of AFE acquisition."
    _reset = 0
    _width = 16
    _offset = 16
    _enums = None


class RegisterWAVEFORM_GEN_REG_3(Register):
    """Register WAVEFORM_GEN_REG_3

    Address: 0x0005 (5)

    Waveform Generator Reg 3
    """

    _name = "WAVEFORM_GEN_REG_3"
    _description = "Waveform Generator Reg 3"
    _address = 5
    _access = Access.RW

    def __init__(self, interface: RegisterMapInterface) -> None:
        self._interface = interface

        # Create instances of bitfields for this register instance
        self.afe_data_acq_time = BitFieldWAVEFORM_GEN_REG_3Afe_data_acq_time()
        self.afe_data_acq_time._set_interface(self._address, interface, self._access)
        self.capture_delay = BitFieldWAVEFORM_GEN_REG_3Capture_delay()
        self.capture_delay._set_interface(self._address, interface, self._access)


class BitFieldTGC_REG_1Tgc_clk_divider(BitField):
    """BitField TGC_CLK_DIVIDER in Register TGC_REG_1

    Clock divider for TGC slope generation (gain ramp rate).
    """

    _name = "TGC_CLK_DIVIDER"
    _description = "Clock divider for TGC slope generation (gain ramp rate)."
    _reset = 0
    _width = 32
    _offset = 0
    _enums = None


class RegisterTGC_REG_1(Register):
    """Register TGC_REG_1

    Address: 0x0006 (6)

    TGC Register 1
    """

    _name = "TGC_REG_1"
    _description = "TGC Register 1"
    _address = 6
    _access = Access.RW

    def __init__(self, interface: RegisterMapInterface) -> None:
        self._interface = interface

        # Create instances of bitfields for this register instance
        self.tgc_clk_divider = BitFieldTGC_REG_1Tgc_clk_divider()
        self.tgc_clk_divider._set_interface(self._address, interface, self._access)


class BitFieldTGC_REG_2Tgc_capture_time(BitField):
    """BitField TGC_CAPTURE_TIME in Register TGC_REG_2

    Duration the TGC gain adjustment is applied after start.
    """

    _name = "TGC_CAPTURE_TIME"
    _description = "Duration the TGC gain adjustment is applied after start."
    _reset = 0
    _width = 32
    _offset = 0
    _enums = None


class RegisterTGC_REG_2(Register):
    """Register TGC_REG_2

    Address: 0x0007 (7)

    TGC Register 2
    """

    _name = "TGC_REG_2"
    _description = "TGC Register 2"
    _address = 7
    _access = Access.RW

    def __init__(self, interface: RegisterMapInterface) -> None:
        self._interface = interface

        # Create instances of bitfields for this register instance
        self.tgc_capture_time = BitFieldTGC_REG_2Tgc_capture_time()
        self.tgc_capture_time._set_interface(self._address, interface, self._access)


class BitFieldTGC_REG_3Tgc_delay_finish(BitField):
    """BitField TGC_DELAY_FINISH in Register TGC_REG_3

    Extra delay before TGC returns to default after final gain.
    """

    _name = "TGC_DELAY_FINISH"
    _description = "Extra delay before TGC returns to default after final gain."
    _reset = 0
    _width = 32
    _offset = 0
    _enums = None


class RegisterTGC_REG_3(Register):
    """Register TGC_REG_3

    Address: 0x0008 (8)

    TGC Register 3
    """

    _name = "TGC_REG_3"
    _description = "TGC Register 3"
    _address = 8
    _access = Access.RW

    def __init__(self, interface: RegisterMapInterface) -> None:
        self._interface = interface

        # Create instances of bitfields for this register instance
        self.tgc_delay_finish = BitFieldTGC_REG_3Tgc_delay_finish()
        self.tgc_delay_finish._set_interface(self._address, interface, self._access)


class BitFieldTGC_REG_4Tgc_delay_start(BitField):
    """BitField TGC_DELAY_START in Register TGC_REG_4

    Delay before TGC gain ramp begins after trigger.
    """

    _name = "TGC_DELAY_START"
    _description = "Delay before TGC gain ramp begins after trigger."
    _reset = 0
    _width = 32
    _offset = 0
    _enums = None


class RegisterTGC_REG_4(Register):
    """Register TGC_REG_4

    Address: 0x0009 (9)

    TGC Register 4
    """

    _name = "TGC_REG_4"
    _description = "TGC Register 4"
    _address = 9
    _access = Access.RW

    def __init__(self, interface: RegisterMapInterface) -> None:
        self._interface = interface

        # Create instances of bitfields for this register instance
        self.tgc_delay_start = BitFieldTGC_REG_4Tgc_delay_start()
        self.tgc_delay_start._set_interface(self._address, interface, self._access)


class BitFieldAFE_TX_RST_REGAfe(BitField):
    """BitField AFE in Register AFE_TX_RST_REG

    Reset AFE.
    """

    _name = "AFE"
    _description = "Reset AFE."
    _reset = 0
    _width = 1
    _offset = 0
    _enums = None


class BitFieldAFE_TX_RST_REGTx(BitField):
    """BitField TX in Register AFE_TX_RST_REG

    Reset TX.
    """

    _name = "TX"
    _description = "Reset TX."
    _reset = 0
    _width = 1
    _offset = 1
    _enums = None


class BitFieldAFE_TX_RST_REGAfe_fpwd_src(BitField):
    """BitField AFE_FPWD_SRC in Register AFE_TX_RST_REG

    AFE fast power-down control source. Enables control from AFE_FPWD_CTRL if set.
    """

    _name = "AFE_FPWD_SRC"
    _description = "AFE fast power-down control source. Enables control from AFE_FPWD_CTRL if set."
    _reset = 0
    _width = 1
    _offset = 2
    _enums = None


class BitFieldAFE_TX_RST_REGAfe_fpwd_ctrl(BitField):
    """BitField AFE_FPWD_CTRL in Register AFE_TX_RST_REG

    Drive AFE fast power-down when set.
    """

    _name = "AFE_FPWD_CTRL"
    _description = "Drive AFE fast power-down when set."
    _reset = 0
    _width = 1
    _offset = 3
    _enums = None


class BitFieldAFE_TX_RST_REGAfe_gpwd_src(BitField):
    """BitField AFE_GPWD_SRC in Register AFE_TX_RST_REG

    AFE global power-down control source. Enables control from AFE_GPWD_CTRL if set.
    """

    _name = "AFE_GPWD_SRC"
    _description = "AFE global power-down control source. Enables control from AFE_GPWD_CTRL if set."
    _reset = 0
    _width = 1
    _offset = 4
    _enums = None


class BitFieldAFE_TX_RST_REGAfe_gpwd_ctrl(BitField):
    """BitField AFE_GPWD_CTRL in Register AFE_TX_RST_REG

    Drive AFE global power-down when set.
    """

    _name = "AFE_GPWD_CTRL"
    _description = "Drive AFE global power-down when set."
    _reset = 0
    _width = 1
    _offset = 5
    _enums = None


class BitFieldAFE_TX_RST_REGTx_en_src(BitField):
    """BitField TX_EN_SRC in Register AFE_TX_RST_REG

    TX enable control source. Enables control from TX_EN_CTRL if set.
    """

    _name = "TX_EN_SRC"
    _description = "TX enable control source. Enables control from TX_EN_CTRL if set."
    _reset = 0
    _width = 1
    _offset = 6
    _enums = None


class BitFieldAFE_TX_RST_REGTx_en_ctrl(BitField):
    """BitField TX_EN_CTRL in Register AFE_TX_RST_REG

    Drive TX_EN when set.
    """

    _name = "TX_EN_CTRL"
    _description = "Drive TX_EN when set."
    _reset = 0
    _width = 1
    _offset = 7
    _enums = None


class RegisterAFE_TX_RST_REG(Register):
    """Register AFE_TX_RST_REG

    Address: 0x000a (10)

    AFE and TX Reset Register
    """

    _name = "AFE_TX_RST_REG"
    _description = "AFE and TX Reset Register"
    _address = 10
    _access = Access.RW

    def __init__(self, interface: RegisterMapInterface) -> None:
        self._interface = interface

        # Create instances of bitfields for this register instance
        self.afe = BitFieldAFE_TX_RST_REGAfe()
        self.afe._set_interface(self._address, interface, self._access)
        self.tx = BitFieldAFE_TX_RST_REGTx()
        self.tx._set_interface(self._address, interface, self._access)
        self.afe_fpwd_src = BitFieldAFE_TX_RST_REGAfe_fpwd_src()
        self.afe_fpwd_src._set_interface(self._address, interface, self._access)
        self.afe_fpwd_ctrl = BitFieldAFE_TX_RST_REGAfe_fpwd_ctrl()
        self.afe_fpwd_ctrl._set_interface(self._address, interface, self._access)
        self.afe_gpwd_src = BitFieldAFE_TX_RST_REGAfe_gpwd_src()
        self.afe_gpwd_src._set_interface(self._address, interface, self._access)
        self.afe_gpwd_ctrl = BitFieldAFE_TX_RST_REGAfe_gpwd_ctrl()
        self.afe_gpwd_ctrl._set_interface(self._address, interface, self._access)
        self.tx_en_src = BitFieldAFE_TX_RST_REGTx_en_src()
        self.tx_en_src._set_interface(self._address, interface, self._access)
        self.tx_en_ctrl = BitFieldAFE_TX_RST_REGTx_en_ctrl()
        self.tx_en_ctrl._set_interface(self._address, interface, self._access)


class BitFieldWAVEFORM_GEN_REG_4N_shots_to_make(BitField):
    """BitField N_SHOTS_TO_MAKE in Register WAVEFORM_GEN_REG_4

    Number of acquisitions (shots) to perform.
    """

    _name = "N_SHOTS_TO_MAKE"
    _description = "Number of acquisitions (shots) to perform."
    _reset = 0
    _width = 16
    _offset = 0
    _enums = None


class BitFieldWAVEFORM_GEN_REG_4Start_capture_time(BitField):
    """BitField START_CAPTURE_TIME in Register WAVEFORM_GEN_REG_4

    Preload of main counter to set deterministic delay from trigger to first TX event.
    """

    _name = "START_CAPTURE_TIME"
    _description = "Preload of main counter to set deterministic delay from trigger to first TX event."
    _reset = 0
    _width = 16
    _offset = 16
    _enums = None


class RegisterWAVEFORM_GEN_REG_4(Register):
    """Register WAVEFORM_GEN_REG_4

    Address: 0x000b (11)

    Waveform Generator Reg 4
    """

    _name = "WAVEFORM_GEN_REG_4"
    _description = "Waveform Generator Reg 4"
    _address = 11
    _access = Access.RW

    def __init__(self, interface: RegisterMapInterface) -> None:
        self._interface = interface

        # Create instances of bitfields for this register instance
        self.n_shots_to_make = BitFieldWAVEFORM_GEN_REG_4N_shots_to_make()
        self.n_shots_to_make._set_interface(self._address, interface, self._access)
        self.start_capture_time = BitFieldWAVEFORM_GEN_REG_4Start_capture_time()
        self.start_capture_time._set_interface(self._address, interface, self._access)


class BitFieldWAVEFORM_GEN_REG_5Refresh_cnt_period(BitField):
    """BitField REFRESH_CNT_PERIOD in Register WAVEFORM_GEN_REG_5

    Period of refresh counter for periodic TR_EN pulses (TX LDO refresh).
    """

    _name = "REFRESH_CNT_PERIOD"
    _description = "Period of refresh counter for periodic TR_EN pulses (TX LDO refresh)."
    _reset = 0
    _width = 16
    _offset = 0
    _enums = None


class BitFieldWAVEFORM_GEN_REG_5Tr_en_on_time(BitField):
    """BitField TR_EN_ON_TIME in Register WAVEFORM_GEN_REG_5

    High-time of TR_EN during each refresh cycle.
    """

    _name = "TR_EN_ON_TIME"
    _description = "High-time of TR_EN during each refresh cycle."
    _reset = 0
    _width = 8
    _offset = 16
    _enums = None


class BitFieldWAVEFORM_GEN_REG_5Fen(BitField):
    """BitField FEN in Register WAVEFORM_GEN_REG_5

    Enable periodic refresh mechanism.
    """

    _name = "FEN"
    _description = "Enable periodic refresh mechanism."
    _reset = 0
    _width = 1
    _offset = 31
    _enums = Regmap_FPGA.EnumFen


class RegisterWAVEFORM_GEN_REG_5(Register):
    """Register WAVEFORM_GEN_REG_5

    Address: 0x000c (12)

    Waveform Generator Reg 5
    """

    _name = "WAVEFORM_GEN_REG_5"
    _description = "Waveform Generator Reg 5"
    _address = 12
    _access = Access.RW

    def __init__(self, interface: RegisterMapInterface) -> None:
        self._interface = interface

        # Create instances of bitfields for this register instance
        self.refresh_cnt_period = BitFieldWAVEFORM_GEN_REG_5Refresh_cnt_period()
        self.refresh_cnt_period._set_interface(self._address, interface, self._access)
        self.tr_en_on_time = BitFieldWAVEFORM_GEN_REG_5Tr_en_on_time()
        self.tr_en_on_time._set_interface(self._address, interface, self._access)
        self.fen = BitFieldWAVEFORM_GEN_REG_5Fen()
        self.fen._set_interface(self._address, interface, self._access)


class BitFieldEXT_INT_TRIG_REGEit(BitField):
    """BitField EIT in Register EXT_INT_TRIG_REG

    Select trigger source.
    """

    _name = "EIT"
    _description = "Select trigger source."
    _reset = 0
    _width = 1
    _offset = 0
    _enums = Regmap_FPGA.EnumEit


class BitFieldEXT_INT_TRIG_REGMim(BitField):
    """BitField MIM in Register EXT_INT_TRIG_REG

    MCU interrupt source select (SPI mux must not be 00).
    """

    _name = "MIM"
    _description = "MCU interrupt source select (SPI mux must not be 00)."
    _reset = 0
    _width = 2
    _offset = 1
    _enums = Regmap_FPGA.EnumMim


class BitFieldEXT_INT_TRIG_REGOtm(BitField):
    """BitField OTM in Register EXT_INT_TRIG_REG

    Output trigger (trigger_o) source select.
    """

    _name = "OTM"
    _description = "Output trigger (trigger_o) source select."
    _reset = 0
    _width = 2
    _offset = 3
    _enums = Regmap_FPGA.EnumOtm


class RegisterEXT_INT_TRIG_REG(Register):
    """Register EXT_INT_TRIG_REG

    Address: 0x000d (13)

    External/Internal Trigger Register
    """

    _name = "EXT_INT_TRIG_REG"
    _description = "External/Internal Trigger Register"
    _address = 13
    _access = Access.RW

    def __init__(self, interface: RegisterMapInterface) -> None:
        self._interface = interface

        # Create instances of bitfields for this register instance
        self.eit = BitFieldEXT_INT_TRIG_REGEit()
        self.eit._set_interface(self._address, interface, self._access)
        self.mim = BitFieldEXT_INT_TRIG_REGMim()
        self.mim._set_interface(self._address, interface, self._access)
        self.otm = BitFieldEXT_INT_TRIG_REGOtm()
        self.otm._set_interface(self._address, interface, self._access)
