[project]
name = "wius-fw-v6-scripts"
version = "0.1.0"
description = "Test scripts used in the development of the WiUS v6 firmware"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.7",
    "numpy>=2.3.4",
    "pandas>=2.3.3",
    "rich>=14.2.0",
]

[dependency-groups]
dev = ["ty>=0.0.1a28"]
